name: Build WindowsGlk x64

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Detect VS toolset
        shell: pwsh
        run: |
          $vs = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath
          if (-not $vs) { throw "No Visual Studio found" }
          if (Test-Path (Join-Path $vs 'VC\Tools\MSVC')) { $pt='v143' } else { $pt='v142' }
          "PLATFORMTOOLSET=$pt" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Using PlatformToolset=$pt"

      # Patcha just GlkDll/Glk.vcxproj för Release|x64
      - name: Configure Release x64 (MFC/Unicode/DLL)
        shell: pwsh
        run: |
          $proj = Join-Path $env:GITHUB_WORKSPACE 'GlkDll\Glk.vcxproj'
          [xml]$x = Get-Content $proj
          $ns = $x.DocumentElement.NamespaceURI
          # Ensure ProjectConfigurations has Release|x64
          $pc = $x.Project.ItemGroup | Where-Object { $_.Label -eq 'ProjectConfigurations' }
          if (-not $pc) {
            $pc = $x.CreateElement('ItemGroup', $ns)
            $pc.SetAttribute('Label','ProjectConfigurations')
            $x.Project.PrependChild($pc) | Out-Null
          }
          $have = $pc.ProjectConfiguration | Where-Object { $_.Include -eq 'Release|x64' }
          if (-not $have) {
            $node = $x.CreateElement('ProjectConfiguration', $ns)
            $node.SetAttribute('Include','Release|x64')
            $c = $x.CreateElement('Configuration', $ns); $c.InnerText = 'Release'
            $p = $x.CreateElement('Platform', $ns);      $p.InnerText = 'x64'
            $node.AppendChild($c) | Out-Null
            $node.AppendChild($p) | Out-Null
            $pc.AppendChild($node) | Out-Null
          }
          $cond = " '`$(Configuration)|`$(Platform)' == 'Release|x64' "
          $grp = $x.Project.PropertyGroup | Where-Object { $_.Condition -eq $cond }
          if (-not $grp) {
             $grp = $x.CreateElement('PropertyGroup', $ns);
             $grp.SetAttribute('Condition',$cond);
             $x.Project.AppendChild($grp) | Out-Null
          }
          $set = @{ ConfigurationType='DynamicLibrary'; UseOfMfc='Dynamic'; CharacterSet='Unicode'; PlatformToolset=$env:PLATFORMTOOLSET }
          foreach ($k in $set.Keys) {
            if ($grp.$k) { $grp.$k.InnerText = $set[$k] }
            else {
              $e=$x.CreateElement($k, $ns);
              $e.InnerText=$set[$k];
              $grp.AppendChild($e) | Out-Null
            }
          }
          $idg = $x.Project.ItemDefinitionGroup | Where-Object { $_.Condition -eq $cond }
          if (-not $idg) {
            $idg = $x.CreateElement('ItemDefinitionGroup', $ns);
            $idg.SetAttribute('Condition',$cond);
            $x.Project.AppendChild($idg) | Out-Null
          }
          if (-not $idg.Link) {
            $lnk = $x.CreateElement('Link', $ns)
            $idg.AppendChild($lnk) | Out-Null
          } else { $lnk = $idg.Link }
          if (-not $lnk.ModuleDefinitionFile) {
            $e=$x.CreateElement('ModuleDefinitionFile', $ns);
            $e.InnerText='Glk.def';
            $lnk.AppendChild($e) | Out-Null
          }
          $x.Save($proj)

      - name: Build Release x64
        run: msbuild GlkDll\Glk.vcxproj /m /p:Configuration=Release /p:Platform=x64 /v:m

      - name: Collect artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force out | Out-Null
          Copy-Item GlkDll\x64\Release\Glk.dll -Destination out -Force
          Copy-Item GlkDll\x64\Release\Glk.lib -Destination out -ErrorAction SilentlyContinue
          Copy-Item GlkDll\x64\Release\Glk.pdb -Destination out -ErrorAction SilentlyContinue
          Get-ChildItem out

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windowsglk-x64
          path: out/*

  make-importlib:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windowsglk-x64
          path: .

      - run: sudo apt-get update && sudo apt-get install -y mingw-w64 binutils-mingw-w64 gendef

      - name: Generate MinGW import lib
        run: |
          gendef Glk.dll
          dlltool -m i386:x86-64 -d Glk.def -D Glk.dll -l libGlk.dll.a
          file Glk.dll libGlk.dll.a || true

      - uses: actions/upload-artifact@v4
        with:
          name: windowsglk-x64-mingw
          path: |
            Glk.def
            libGlk.dll.a
