name: Build WindowsGlk x64

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Prepare folder layout (<root>/Adv/Glk and <root>/Libraries)
        shell: pwsh
        run: |
          $ROOT = Resolve-Path (Join-Path $env:GITHUB_WORKSPACE '..')
          $ADV  = Join-Path $ROOT 'Adv\Glk'
          New-Item -ItemType Directory -Force (Split-Path $ADV) | Out-Null
          # Flytta/kopiera in dagens repo till <root>/Adv/Glk
          $ROOT = Resolve-Path (Join-Path $env:GITHUB_WORKSPACE '..')
          $ADV  = Join-Path $ROOT 'Adv\Glk'

          New-Item -ItemType Directory -Force (Split-Path $ADV) | Out-Null
          New-Item -ItemType Directory -Force $ADV | Out-Null     # ← se till att Glk/ finns

          robocopy "$env:GITHUB_WORKSPACE" "$ADV" /MIR /NFL /NDL /NJH /NJS
          $rc = $LASTEXITCODE; if ($rc -ge 8) { throw "robocopy failed with exit code $rc" } else { $LASTEXITCODE = 0 }

          "ROOT=$ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          "ADV=$ADV"   | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "ROOT=$ROOT"
          Write-Host "ADV=$ADV"

      - name: Fetch Kinder Libraries repo
        shell: pwsh
        run: |
          cd $env:ROOT
          git clone https://github.com/DavidKinder/Libraries.git Libraries

      - name: Fetch libogg + libvorbis sources
        shell: pwsh
        run: |
          cd $env:ROOT
          $ProgressPreference = 'SilentlyContinue'

          # libogg
          iwr https://downloads.xiph.org/releases/ogg/libogg-1.3.5.zip -OutFile ogg.zip
          Expand-Archive ogg.zip -DestinationPath ogg -Force
          $o = Get-ChildItem ogg -Directory | Select-Object -First 1
          robocopy $o.FullName (Join-Path $PWD 'Libraries\libogg') /MIR /NFL /NDL /NJH /NJS
          $rc=$LASTEXITCODE; if ($rc -ge 8){ throw "robocopy ogg rc=$rc" } else { $LASTEXITCODE=0 }

          # libvorbis
          iwr https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.zip -OutFile vorbis.zip
          Expand-Archive vorbis.zip -DestinationPath vorbis -Force
          $v = Get-ChildItem vorbis -Directory | Select-Object -First 1
          robocopy $v.FullName (Join-Path $PWD 'Libraries\libvorbis') /MIR /NFL /NDL /NJH /NJS
          $rc=$LASTEXITCODE; if ($rc -ge 8){ throw "robocopy vorbis rc=$rc" } else { $LASTEXITCODE=0 }

      - name: Fetch zlib + libpng + libjpeg6b
        shell: pwsh
        run: |
          cd $env:ROOT
          $ProgressPreference = 'SilentlyContinue'
          $ErrorActionPreference = 'Stop'

          function Get-Zip {
            param([string]$Url,[string]$Out)
            & curl.exe -L --retry 5 --retry-delay 3 -o $Out $Url
            if (-not (Test-Path $Out)) { throw "download failed: $Url" }
          }

          # zlib
          Get-Zip 'https://zlib.net/zlib131.zip' 'zlib.zip'
          mkdir ztmp -Force | Out-Null
          tar.exe -xf zlib.zip -C ztmp
          $z = Get-ChildItem ztmp -Directory | Select-Object -First 1
          robocopy $z.FullName (Join-Path $PWD 'Libraries\zlib') /MIR /NFL /NDL /NJH /NJS
          $rc=$LASTEXITCODE; if ($rc -ge 8){ throw "robocopy zlib rc=$rc" } else { $LASTEXITCODE=0 }

          # libpng
          Get-Zip 'https://download.sourceforge.net/libpng/lpng1640.zip' 'libpng.zip'
          mkdir ptmp -Force | Out-Null
          tar.exe -xf libpng.zip -C ptmp
          $p = Get-ChildItem ptmp -Directory | Select-Object -First 1
          robocopy $p.FullName (Join-Path $PWD 'Libraries\libpng') /MIR /NFL /NDL /NJH /NJS
          $rc=$LASTEXITCODE; if ($rc -ge 8){ throw "robocopy libpng rc=$rc" } else { $LASTEXITCODE=0 }
          Copy-Item (Join-Path $PWD 'Libraries\libpng\scripts\pnglibconf.h.prebuilt') (Join-Path $PWD 'Libraries\libpng\pnglibconf.h') -Force

          # libjpeg 6b
          Get-Zip 'https://download.sourceforge.net/libjpeg/jpegsrc.v6b.tar.gz' 'jpeg.tgz'
          mkdir jtmp -Force | Out-Null
          tar.exe -xzf jpeg.tgz -C jtmp
          $j = Get-ChildItem jtmp -Directory | Select-Object -First 1
          robocopy $j.FullName (Join-Path $PWD 'Libraries\jpeg') /MIR /NFL /NDL /NJH /NJS
          $rc=$LASTEXITCODE; if ($rc -ge 8){ throw "robocopy jpeg rc=$rc" } else { $LASTEXITCODE=0 }
          Copy-Item (Join-Path $PWD 'Libraries\jpeg\jconfig.vc') (Join-Path $PWD 'Libraries\jpeg\jconfig.h') -Force
          (Get-Content (Join-Path $PWD 'Libraries\jpeg\jmorecfg.h')) -replace '#ifndef XMD_H','#if !defined(XMD_H) && !defined(_BASETSD_H_)' |
            Set-Content (Join-Path $PWD 'Libraries\jpeg\jmorecfg.h')
          $jm = Get-Content (Join-Path $PWD 'Libraries\jpeg\jmorecfg.h')
          if ($jm -notmatch '#ifndef FAR') {
            Add-Content (Join-Path $PWD 'Libraries\jpeg\jmorecfg.h') "`r`n#ifndef FAR`r`n#ifdef NEED_FAR_POINTERS`r`n#define FAR  far`r`n#else`r`n#define FAR`r`n#endif`r`n#endif"
          }

      - name: Detect VS toolset
        shell: pwsh
        run: |
          $vs = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath
          if (-not $vs) { throw "No Visual Studio found" }
          if (Test-Path (Join-Path $vs 'VC\Tools\MSVC')) { $pt='v143' } else { $pt='v142' }
          "PLATFORMTOOLSET=$pt" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Using PlatformToolset=$pt"

      # Patcha just GlkDll/Glk.vcxproj för Release|x64
      - name: Configure Release x64 (MFC/Unicode/DLL)
        shell: pwsh
        run: |
          $proj = Join-Path $env:GITHUB_WORKSPACE 'GlkDll\Glk.vcxproj'
          [xml]$x = Get-Content $proj
          $ns = $x.DocumentElement.NamespaceURI
          # Ensure ProjectConfigurations has Release|x64
          $pc = $x.Project.ItemGroup | Where-Object { $_.Label -eq 'ProjectConfigurations' }
          if (-not $pc) {
            $pc = $x.CreateElement('ItemGroup', $ns)
            $pc.SetAttribute('Label','ProjectConfigurations')
            $x.Project.PrependChild($pc) | Out-Null
          }
          $have = $pc.ProjectConfiguration | Where-Object { $_.Include -eq 'Release|x64' }
          if (-not $have) {
            $node = $x.CreateElement('ProjectConfiguration', $ns)
            $node.SetAttribute('Include','Release|x64')
            $c = $x.CreateElement('Configuration', $ns); $c.InnerText = 'Release'
            $p = $x.CreateElement('Platform', $ns);      $p.InnerText = 'x64'
            $node.AppendChild($c) | Out-Null
            $node.AppendChild($p) | Out-Null
            $pc.AppendChild($node) | Out-Null
          }
          $cond = " '`$(Configuration)|`$(Platform)' == 'Release|x64' "
          $grp = $x.Project.PropertyGroup | Where-Object { $_.Condition -eq $cond }
          if (-not $grp) {
             $grp = $x.CreateElement('PropertyGroup', $ns);
             $grp.SetAttribute('Condition',$cond);
             $x.Project.AppendChild($grp) | Out-Null
          }
          $set = @{ ConfigurationType='DynamicLibrary'; UseOfMfc='Dynamic'; CharacterSet='Unicode'; PlatformToolset=$env:PLATFORMTOOLSET }
          foreach ($k in $set.Keys) {
            if ($grp.$k) { $grp.$k.InnerText = $set[$k] }
            else {
              $e=$x.CreateElement($k, $ns);
              $e.InnerText=$set[$k];
              $grp.AppendChild($e) | Out-Null
            }
          }
          $idg = $x.Project.ItemDefinitionGroup | Where-Object { $_.Condition -eq $cond }
          if (-not $idg) {
            $idg = $x.CreateElement('ItemDefinitionGroup', $ns);
            $idg.SetAttribute('Condition',$cond);
            $x.Project.AppendChild($idg) | Out-Null
          }
          if (-not $idg.Link) {
            $lnk = $x.CreateElement('Link', $ns)
            $idg.AppendChild($lnk) | Out-Null
          } else { $lnk = $idg.Link }
          if (-not $lnk.ModuleDefinitionFile) {
            $e=$x.CreateElement('ModuleDefinitionFile', $ns);
            $e.InnerText='Glk.def';
            $lnk.AppendChild($e) | Out-Null
          }
          $x.Save($proj)

      - name: Build Release x64
        run: msbuild GlkDll\Glk.vcxproj /m /p:Configuration=Release /p:Platform=x64 /v:m

      - name: Collect artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force out | Out-Null
          Copy-Item GlkDll\x64\Release\Glk.dll -Destination out -Force
          Copy-Item GlkDll\x64\Release\Glk.lib -Destination out -ErrorAction SilentlyContinue
          Copy-Item GlkDll\x64\Release\Glk.pdb -Destination out -ErrorAction SilentlyContinue
          Get-ChildItem out

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windowsglk-x64
          path: out/*

  make-importlib:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windowsglk-x64
          path: .

      - run: sudo apt-get update && sudo apt-get install -y mingw-w64 binutils-mingw-w64 gendef

      - name: Generate MinGW import lib
        run: |
          gendef Glk.dll
          dlltool -m i386:x86-64 -d Glk.def -D Glk.dll -l libGlk.dll.a
          file Glk.dll libGlk.dll.a || true

      - uses: actions/upload-artifact@v4
        with:
          name: windowsglk-x64-mingw
          path: |
            Glk.def
            libGlk.dll.a
